.\" $Id$
.TH ARTSTUDIOTOPPM 1 1999-06-12 "Softwolves Software" ""
artstudiotoppm \- convert Art Studio to PPM format
.SH SYNOPSIS
.B artstudiotoppm
[inputfile [outputfile]]
.SH DESCRIPTION
.B artstudiotoppm
is a program that is used to convert between the Art Studio
image format (a popular Commodore 64 drawing program) and
the portable pixmap format, ppm.
.SH "DISTRIBUTED FILES"
These files comes with the
.B artstudiotoppm
distribution:
.PD 0
.TP
.I COPYING
The GNU General Public License.
.TP
.I Makefile
File used by
.BR make (1)
to automate compilation.
.TP
.I artstudiotoppm.c
Source code for the program.
.TP
.I artstudiotoppm.1
This manual page.
.TP
.I a2p.exe
DOS executable.
.PD
.SH BUGS
The program does not handle Advanced Art Studio files
(multi-colour).
.SH "SEE ALSO"
.BR ppm (5)
.SH AUTHOR
ARTSTUDIOTOPPM was written by Peter Karlsson.
If you have bug-reports or questions, mail them to pk@abc.se.
.PP
A Softwolves Software (tm) Release in 1999.
.PP
http://www.softwolves.pp.se/wolves/
.PP
This program is released under the GNU Public License.
